#include "Pro_h/SeismicIO.h"

namespace SeismicIO {

//segy格式数据读取 IEEE IBM
	// 交换 4 字节大端转小端 (int/float)
	uint32_t swap4byte(uint32_t value) {
		return ((value & 0xFF000000) >> 24) |
			((value & 0x00FF0000) >> 8) |
			((value & 0x0000FF00) << 8) |
			((value & 0x000000FF) << 24);
	}
	// 交换 2 字节大端转小端 (short)
	int16_t swap2byte(int16_t value) {
		// 强制转换为无符号进行移位，防止符号位扩展问题
		uint16_t uval = static_cast<uint16_t>(value);
		return static_cast<int16_t>((uval >> 8) | (uval << 8));
	}
	// IBM Float 转 IEEE Float
	float ibm2float(uint32_t x) {
		if (x == 0) return 0.0f;

		// IBM 格式: 
		// Bit 0: Sign
		// Bit 1-7: Exponent (Base 16, Bias 64)
		// Bit 8-31: Mantissa (24 bits)

		int sign = (x >> 31) & 0x01;
		int exponent = (x >> 24) & 0x7F;
		int mantissa = x & 0x00FFFFFF;

		// IBM 指数是 16 进制的，Bias 为 64
		// 值 = (-1)^sign * 0.mantissa * 16^(exponent - 64)

		// 优化：16^e = (2^4)^e = 2^(4e)
		// 优化：将除法 pow(2, 24) 变为乘法

		float f_mant = static_cast<float>(mantissa) * 5.96046448e-8f; // * 1.0 / pow(2, 24)
		float result = (1.0f - 2.0f * sign) * f_mant * std::pow(16.0f, exponent - 64);

		return result;
	}
	// SEGY 读取
	std::vector<std::vector<float>> readSegyFile2D(std::string inputfile) {
		std::ifstream filein(inputfile, std::ios::binary);

		// 1. 错误检查：打开失败立即返回
		if (!filein.is_open()) {
			std::cerr << "Error: Cannot open file " << inputfile << std::endl;
			return {};
		}

		// 2. 读取卷头
		// 3200字节 文本卷头 (EBCDIC or ASCII) - 暂时跳过不处理
		filein.seekg(3200, std::ios::beg);

		// 400字节 二进制卷头
		std::vector<char> binHeader(400);
		filein.read(binHeader.data(), 400);

		// 读取采样点数 (Bytes 20-21 in binary header, i.e., index 20)
		// 注意：SEGY 标准是大端序 (Big-Endian)
		int16_t* pSampleCount = reinterpret_cast<int16_t*>(&binHeader[20]);
		int trace_length = swap2byte(*pSampleCount);

		// 读取数据格式代码 (Bytes 24-25 in binary header, i.e., index 24)
		// 1 = IBM Float, 5 = IEEE Float
		int16_t* pFormatCode = reinterpret_cast<int16_t*>(&binHeader[24]);
		int format_code = swap2byte(*pFormatCode);

		// 3. 计算道数
		filein.seekg(0, std::ios::end);
		long long fileSize = filein.tellg();
		long long trace_total_bytes = 240 + 4 * static_cast<long long>(trace_length); // 道头240字节 + 数据
		long long traces = (fileSize - 3600) / trace_total_bytes;

		std::cout << "File: " << inputfile << "\n"
			<< "Trace Length: " << trace_length << "\n"
			<< "Total Traces: " << traces << "\n"
			<< "Format Code: " << format_code << (format_code == 1 ? " (IBM)" : (format_code == 5 ? " (IEEE)" : " (Unknown)"))
			<< std::endl;

		if (traces <= 0 || trace_length <= 0) {
			std::cerr << "Error: Invalid trace count or length." << std::endl;
			return {};
		}

		// 4. 读取数据
		filein.seekg(3600, std::ios::beg); // 跳回第一道开始处

		// 预分配内存，避免 vector 动态扩容
		std::vector<std::vector<float>> dataArray(traces, std::vector<float>(trace_length));

		// 缓冲区：每次读取一道的数据部分 (4 bytes * length)
		// 道头 240 字节
		std::vector<char> traceHeader(240);
		std::vector<uint32_t> rawData(trace_length);

		for (int i = 0; i < traces; i++) {
			if (i % 10000 == 0 && i > 0) std::cout << "Reading trace: " << i << std::endl;

			// 读取道头和道数据
			filein.read(traceHeader.data(), 240);
			filein.read(reinterpret_cast<char*>(rawData.data()), trace_length * 4);

			for (int j = 0; j < trace_length; j++) {
				// SEGY 是大端序，PC 是小端序，必须交换字节
				uint32_t val = swap4byte(rawData[j]);

				if (format_code == 1) {
					// IBM Floating Point
					dataArray[i][j] = ibm2float(val);
				}
				else if (format_code == 5) {
					// IEEE Floating Point
					// 使用 memcpy 进行位转换，严谨且安全
					float f_val;
					std::memcpy(&f_val, &val, sizeof(float));
					dataArray[i][j] = f_val;
				}
				else {
					// 默认为 IEEE 或者做其他处理
					float f_val;
					std::memcpy(&f_val, &val, sizeof(float));
					dataArray[i][j] = f_val;
				}
			}
		}

		filein.close();
		return dataArray;
	}
	// 保存二维数组为 SEGY 格式 (IEEE Float)
	void writeSegyFile2D(const std::vector<std::vector<float>>& dataArray, const std::string outputfile, float dt = 0.002f) {
		std::ofstream fileout(outputfile, std::ios::binary);
		if (!fileout.is_open()) {
			std::cerr << "Error: Cannot create file " << outputfile << std::endl;
			return;
		}

		int num_traces = dataArray.size();
		if (num_traces == 0) return;
		int num_samples = dataArray[0].size();

		// ---------------------------------------------------------
		// 1. 写入文本卷头 (3200 bytes)
		// ---------------------------------------------------------
		// 通常这里写入 EBCDIC 编码的描述信息，这里简单填充空格或 ASCII 信息
		std::vector<char> textHeader(3200, ' ');
		std::string desc = "C01 SEGY FILE GENERATED BY SEIS-FDM-TOOL";
		std::memcpy(textHeader.data(), desc.c_str(), desc.size());

		// 转换 ASCII -> EBCDIC (可选，为了最大兼容性通常需要，但很多现代软件也能读 ASCII)
		// 这里为了简化，直接写入 ASCII，如果需要严格标准，需要一个转换表。
		fileout.write(textHeader.data(), 3200);

		// ---------------------------------------------------------
		// 2. 写入二进制卷头 (400 bytes)
		// ---------------------------------------------------------
		std::vector<char> binHeader(400, 0);

		// 设置关键字段 (注意大端序转换)
		// Byte 17-18: 采样间隔 (微秒)
		int16_t interval_us = static_cast<int16_t>(dt * 1000000);
		int16_t be_interval = swap2byte(interval_us);
		std::memcpy(&binHeader[16], &be_interval, 2);

		// Byte 21-22: 每道采样点数
		int16_t samples = static_cast<int16_t>(num_samples);
		int16_t be_samples = swap2byte(samples);
		std::memcpy(&binHeader[20], &be_samples, 2);

		// Byte 25-26: 数据格式代码 (5 = IEEE Float)
		int16_t format = swap2byte(5);
		std::memcpy(&binHeader[24], &format, 2);

		fileout.write(binHeader.data(), 400);

		// ---------------------------------------------------------
		// 3. 写入道数据 (Trace Header + Data)
		// ---------------------------------------------------------
		std::vector<char> traceHeader(240, 0);

		for (int i = 0; i < num_traces; ++i) {
			// --- 填充道头 (240 bytes) ---
			// 每次清零或复用，这里简单清零
			std::fill(traceHeader.begin(), traceHeader.end(), 0);

			// Byte 1-4: 线号/道顺序号 (Trace sequence number within line)
			int32_t trace_seq = swap4byte(i + 1);
			std::memcpy(&traceHeader[0], &trace_seq, 4);

			// Byte 115-116: 采样点数
			std::memcpy(&traceHeader[114], &be_samples, 2);

			// Byte 117-118: 采样间隔 (微秒)
			std::memcpy(&traceHeader[116], &be_interval, 2);

			// 写入道头
			fileout.write(traceHeader.data(), 240);

			// --- 写入数据 (IEEE Float Big-Endian) ---
			for (int j = 0; j < num_samples; ++j) {
				float val = dataArray[i][j];

				// 强转为 uint32 进行位操作
				uint32_t val_int;
				std::memcpy(&val_int, &val, 4);

				// 转换为大端序
				uint32_t be_val = swap4byte(val_int);

				fileout.write(reinterpret_cast<char*>(&be_val), 4);
			}
		}

		fileout.close();
		std::cout << "SEGY Saved: " << outputfile << " (" << num_traces << "x" << num_samples << ")" << std::endl;
	}
	// 重载2：从 1D Flat vector 写入 (高性能，无拷贝)
	void writeSegyFile2D(const std::vector<float>& flatData, int nTraces, int nSamples, const std::string& outputfile, float dt) {
		std::ofstream fileout(outputfile, std::ios::binary);
		if (!fileout.is_open()) return;

		// 1. Text Header
		std::vector<char> textHeader(3200, ' ');
		std::string desc = "SEGY GENERATED BY SEISMIC-IO LIB (FLAT)";
		std::memcpy(textHeader.data(), desc.c_str(), desc.size());
		fileout.write(textHeader.data(), 3200);

		// 2. Binary Header
		std::vector<char> binHeader(400, 0);
		int16_t interval_us = swap2byte(static_cast<int16_t>(dt * 1000000));
		std::memcpy(&binHeader[16], &interval_us, 2);

		int16_t ns_be = swap2byte(static_cast<int16_t>(nSamples));
		std::memcpy(&binHeader[20], &ns_be, 2);

		int16_t fmt_be = swap2byte(5); // IEEE
		std::memcpy(&binHeader[24], &fmt_be, 2);
		fileout.write(binHeader.data(), 400);

		// 3. Data
		std::vector<char> traceHeader(240, 0);
		for (int i = 0; i < nTraces; ++i) {
			std::fill(traceHeader.begin(), traceHeader.end(), 0);
			int32_t seq = swap4byte(i + 1);
			std::memcpy(&traceHeader[0], &seq, 4);
			std::memcpy(&traceHeader[114], &ns_be, 2);
			std::memcpy(&traceHeader[116], &interval_us, 2);
			fileout.write(traceHeader.data(), 240);

			size_t offset = (size_t)i * nSamples;
			for (int j = 0; j < nSamples; ++j) {
				float val = flatData[offset + j]; // 直接访问
				uint32_t val_int;
				std::memcpy(&val_int, &val, 4);
				val_int = swap4byte(val_int);
				fileout.write(reinterpret_cast<char*>(&val_int), 4);
			}
		}
		fileout.close();
	}
	// 文本写入实现
	void writeTextFile2D(const std::vector<std::vector<float>>& dataArray, const std::string& outputfile) {
		std::ofstream fileout(outputfile);
		if (!fileout.is_open()) return;

		fileout.precision(6);
		fileout << std::fixed;

		for (size_t i = 0; i < dataArray.size(); i++) {
			for (size_t j = 0; j < dataArray[i].size(); j++) {
				fileout << dataArray[i][j];
				if (j < dataArray[i].size() - 1) fileout << ",";
			}
			fileout << "\n";
		}
		fileout.close();
	}

} // namespace SeismicIO


namespace SeismicUtils {
	/**
	 * @brief 生成雷克子波 (Ricker Wavelet)
	 *
	 * 公式: A = (1 - 2 * (pi * f * t)^2) * exp(-(pi * f * t)^2)
	 *
	 * @param f     主频 (Dominant frequency in Hz)
	 * @param dt    时间采样间隔 (Time step in seconds)
	 * @param nt    采样点数 (Number of time samples)
	 * @param delay 子波延迟时间 (Time shift in seconds), 也就是峰值出现的时间
	 * @return std::vector<float> 返回生成的子波序列
	 */
	std::vector<float> generateRickerWavelet(float f, float dt, int nt, float delay) {
		if (nt <= 0) return {};

		std::vector<float> wavelet(nt);

		// 预计算常量，避免在循环中重复计算
		// 使用 double 保证中间计算精度，最后转回 float
		const double PI = M_PI;
		const double pi_f = PI * f;
		const double pi_f_sq = pi_f * pi_f; // (pi * f)^2

		for (int it = 0; it < nt; ++it) {
			double t = it * dt - delay;
			double a = pi_f_sq * t * t; // (pi * f * t)^2

			// Ricker 公式: (1 - 2a) * e^(-a)
			wavelet[it] = static_cast<float>((1.0 - 2.0 * a) * std::exp(-a));
		}

		return wavelet;
	}

	/**
	 * @brief 计算有限差分系数 (Finite Difference Coefficients)
	 *
	 * 基于泰勒展开求解线性方程组 A * C = B，计算一阶导数的差分系数。
	 *
	 * @param o 差分阶数 (Order)，即单侧系数的个数。例如 o=4 对应 8 阶精度。
	 * @param s 网格类型: 'r' (Regular grid, 常规网格) 或 's' (Staggered grid, 交错网格)
	 * @return Eigen::VectorXd 包含计算出的系数向量
	 */
	Eigen::VectorXd calculateDiffCoefficients(int o, char s ) {
		if (o <= 0) {
			throw std::invalid_argument("Order 'o' must be positive.");
		}
		if (s != 'r' && s != 's') {
			throw std::invalid_argument("Grid type 's' must be 'r' (regular) or 's' (staggered).");
		}

		// 初始化矩阵 A 和向量 B
		Eigen::MatrixXd A(o, o);
		Eigen::VectorXd B = Eigen::VectorXd::Zero(o);

		// 根据网格类型构建方程组
		if (s == 'r') {
			// 常规网格 (Regular Grid)
			// 求解目标通常是: f'(x) ~ sum( c_j * (f(x+j) - f(x-j)) ) / dx
			// 对应泰勒展开项: j, j^3, j^5...
			B(0) = 0.5; // 对应一阶导数项系数 (因为是双侧差分 f(x+h)-f(x-h)，所以系数和为1，单侧为0.5)

			for (int i = 0; i < o; ++i) {
				double exp = 2.0 * (i + 1) - 1.0; // 指数: 1, 3, 5...
				for (int j = 0; j < o; ++j) {
					double base = static_cast<double>(j + 1); // 底数: 1, 2, 3...
					A(i, j) = std::pow(base, exp);
				}
			}
		}
		else { // s == 's'
			// 交错网格 (Staggered Grid)
			// 求解目标通常是: f'(x) ~ sum( c_j * (f(x + (j-0.5)) - f(x - (j-0.5))) ) / dx
			// 对应偏移量: 1/2, 3/2, 5/2...
			B(0) = 1.0; // 交错网格泰勒展开通常按整项匹配

			for (int i = 0; i < o; ++i) {
				double exp = 2.0 * (i + 1) - 1.0; // 指数: 1, 3, 5...
				for (int j = 0; j < o; ++j) {
					double base = 2.0 * (j + 1) - 1.0; // 底数 (代表半网格倍数): 1, 3, 5... (实际上代表 0.5, 1.5...)
					A(i, j) = std::pow(base, exp);
				}
			}
		}

		// 求解线性方程组
		// 优先使用 QR 分解，如果失败尝试 SVD 分解
		Eigen::VectorXd C;
		try {
			C = A.colPivHouseholderQr().solve(B);
		}
		catch (...) {
			// 降级处理：使用 SVD 求解奇异矩阵或病态矩阵
			C = A.bdcSvd(Eigen::ComputeThinU | Eigen::ComputeThinV).solve(B);
		}

		return C;
	}

	// 功能函数实现
	std::vector<std::vector<float>> Grid_resample(const std::vector<std::vector<float>>& dataArray, float target_spacing, float original_spacing) {

		if (dataArray.empty() || dataArray[0].empty()) return {};

		int data_znum = dataArray.size();       // 原始 Z 点数
		int data_xnum = dataArray[0].size();    // 原始 X 点数

		// 1. 计算物理尺寸 (Physical Dimensions)
		// 假设原始数据从 0 开始，总长度 = (点数 - 1) * 间距
		float physical_width = (data_xnum - 1) * original_spacing;
		float physical_depth = (data_znum - 1) * original_spacing; // 假设原始 dx=dz

		// 2. 计算新的网格点数
		// 新点数 = 总长度 / 新间距 + 1
		int grid_xnum = static_cast<int>(physical_width / target_spacing) + 1;
		int grid_znum = static_cast<int>(physical_depth / target_spacing) + 1;

		std::cout << "Resample: " << data_xnum << "x" << data_znum
			<< " -> " << grid_xnum << "x" << grid_znum << std::endl;

		// 3. 初始化新网格
		std::vector<std::vector<float>> grid_data(grid_znum, std::vector<float>(grid_xnum, 0.0f));

		// 4. 预计算映射比例 (Ratio)
		// 我们需要把新网格索引 j 映射回旧网格索引 data_j
		// 公式: old_index = new_index * (target_spacing / original_spacing)
		float ratio = target_spacing / original_spacing;

		// 5. 执行插值 (最近邻插值 Nearest Neighbor)
		// 如果需要更高质量，可以改为双线性插值 (Bilinear Interpolation)
		for (int i = 0; i < grid_znum; ++i) {
			// 计算对应的原始 Z 索引
			// 加上 0.5 是为了四舍五入 (round)，实现最近邻
			int data_i = static_cast<int>(i * ratio + 0.5f);

			// 边界钳位 (Clamping)，防止浮点误差导致越界
			if (data_i >= data_znum) data_i = data_znum - 1;

			for (int j = 0; j < grid_xnum; ++j) {
				// 计算对应的原始 X 索引
				int data_j = static_cast<int>(j * ratio + 0.5f);

				// 边界钳位
				if (data_j >= data_xnum) data_j = data_xnum - 1;

				grid_data[i][j] = dataArray[data_i][data_j];
			}
		}

		return grid_data;
	}
	//2d to 1d
	std::vector<float> flatten_2d(const std::vector<std::vector<float>>& vec2d) {
		if (vec2d.empty()) return {};
		int rows = vec2d.size();
		int cols = vec2d[0].size();
		std::vector<float> flat(rows * cols);
#pragma omp parallel for
		for (int i = 0; i < rows; ++i) {
			for (int j = 0; j < cols; ++j) {
				flat[i * cols + j] = vec2d[i][j];
			}
		}
		return flat;
	}
	//模型扩边
	std::vector<std::vector<float>> addPmlToGrid(const std::vector<std::vector<float>>& grid_input, int npml) {
		// 1. 基本检查
		if (grid_input.empty() || grid_input[0].empty()) return {};

		int NX = grid_input.size();
		int NZ = grid_input[0].size();

		// 2. 初始化输出网格
		int out_NX = NX + 2 * npml;
		int out_NZ = NZ + 2 * npml;
		std::vector<std::vector<float>> grid_output(out_NX, std::vector<float>(out_NZ, 0.0f));

		// 3. 定义有效数据的边界索引
		// 如果你的数据最外圈 (NX-1) 是 0，必须用 NX-2 也就是倒数第二行作为有效边界
		int valid_max_x = NX - 2;
		int valid_max_z = NZ - 2;
		// 如果以后数据修复了，想用最外圈，改成 NX - 1 即可

		// 4. 使用钳位逻辑填充 (Clamp)
		for (int i = 0; i < out_NX; ++i) {
			// 计算映射回原网格的 X 坐标 (限制在 0 到 valid_max_x 之间)
			int src_i = std::max(0, std::min(i - npml, valid_max_x));

			for (int j = 0; j < out_NZ; ++j) {
				// 计算映射回原网格的 Z 坐标 (限制在 0 到 valid_max_z 之间)
				int src_j = std::max(0, std::min(j - npml, valid_max_z));

				grid_output[i][j] = grid_input[src_i][src_j];
			}
		}

		return grid_output;
	}
	// 定义一个函数来进行矩阵转置
	std::vector<std::vector<float>> transposeMatrix(const std::vector<std::vector<float>>& matrix) {
		if (matrix.empty()) return {};
		int rows = matrix.size();
		int cols = matrix[0].size();
		std::vector<std::vector<float>> transposed(cols, std::vector<float>(rows));

		// 使用简单的分块优化或OpenMP加速转置
#pragma omp parallel for
		for (int i = 0; i < rows; ++i) {
			for (int j = 0; j < cols; ++j) {
				transposed[j][i] = matrix[i][j];
			}
		}
		return transposed;
	}
	// 优化 1: 使用 const 引用传递 (const vector<...>&)，避免深拷贝输入数据
	std::vector<std::vector<float>> concatMatrix2D(const std::vector<std::vector<float>>& d1, const std::vector<std::vector<float>>& d2, int flag) {

		// 基础检查：防止空数据崩溃（可选，视具体需求而定）
		if (d1.empty()) return d2;
		if (d2.empty()) return d1;

		if (flag == 1) {
			// --- 按行拼接 (垂直拼接) ---

			// 检查维度一致性 (可选，取决于业务逻辑是否允许不同宽度的拼接)
			if (d1[0].size() != d2[0].size()) {
				throw std::invalid_argument("按行拼接时，两个矩阵的列数必须相同");
			}

			std::vector<std::vector<float>> result;
			// 优化 2: 预分配外层 vector 内存，避免多次 realloc
			result.reserve(d1.size() + d2.size());

			// 优化 3: 使用 insert 区间插入，比循环 push_back 更高效
			result.insert(result.end(), d1.begin(), d1.end());
			result.insert(result.end(), d2.begin(), d2.end());

			return result;
		}
		else {
			// --- 按列拼接 (水平拼接) ---

			if (d1.size() != d2.size()) {
				throw std::invalid_argument("按列拼接时，两个矩阵的行数必须相同");
			}

			int rows = d1.size();
			// 预分配外层行数
			std::vector<std::vector<float>> result(rows);

			// 使用 OpenMP 加速大矩阵的拼接 (如果在 FDM 循环外调用)
			// #pragma omp parallel for 
			for (int i = 0; i < rows; ++i) {
				// 计算新行的总大小
				size_t newSize = d1[i].size() + d2[i].size();

				// 优化 2: 预分配内层 vector 内存
				result[i].reserve(newSize);

				// 优化 3: 使用 insert 区间插入
				result[i].insert(result[i].end(), d1[i].begin(), d1[i].end());
				result[i].insert(result[i].end(), d2[i].begin(), d2[i].end());
			}

			return result;
		}
	}


}//namespace SeismicUtils